### ISSUE TITLE
Comment count is incorrect on the web interface

### ISSUE THREAD

**Issue by Lastique** [cppalliance/boost-mailman#2]
https://lists.preview.boost.org/archives/list/boost@lists.preview.boost.org/thread/NJKVW7KRLSALK2VQ7XW7LPBIB22ESM7E/

There are two replies to the original message, but it says "0 comments" on the right. It also shows 0 comments in the thread list.

![Screenshot_20240604_233310](https://github.com/cppalliance/boost-mailman/assets/1589747/b530a4ba-b139-4c34-9188-f40a0affbd69)

**Comment by sdarwin** [comment]
That same thread now says "2 comments 2 participants" instead of "0 comments 1 participant".

There are hourly, daily, minutely cron tasks running.   One of those updates the count. At least within 1 day, if not sooner.     I agree that instantaneous would be better. Mailman3 is not perfect.  :-)

**Comment by sdarwin** [comment]
Improved since last comment.   
It turns out a django queuing service `qcluster` wasn't running. Now comments, participants are updated within a few seconds.

**Comment by sdarwin** [comment]
This was fixed with the `qcluster` service. Closing issue.
