### ISSUE TITLE
Show username instead of email address on the web interface

### ISSUE THREAD

**Issue by Lastique** [cppalliance/boost-mailman#3]
When a message to the ML was sent using an email client (not on the web interface), the web interface displays user's email instead of user name that was specified during registration. It would be better to always show the user name, for consistency and to reduce exposure of email addresses.

![Screenshot_20240604_233310](https://github.com/cppalliance/boost-mailman/assets/1589747/3228cca5-66da-43ba-bfe6-e429e503b2b2)

**Comment by sdarwin** [comment]
I believe the report in this issue may be inverted/backwards.  

- When sending email using Gmail it shows `From: My Name <myemail@gmail.com>`  .  The "My Name" is then displayed in Hyperkitty.
- When sending email from Hyperkitty's web interface directly, the first choice is the user's "display name" setting, with first and last name.  Most likely, you did not configure a "display name".   In the absence of this variable, it falls back to email address.  The solution is to configure a first and last name in the web interface.

**Comment by sdarwin** [comment]
The fix is for the user to add their first and last name in the web interface, when posting from the web.  
Closing issue. Can be reopened if there are still problems.
